import type { MetadataRoute } from 'next'

const BASE = 'https://www.digi-home-design.com'

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes: string[] = [
    '/',
    '/chi-siamo/storia',
    '/chi-siamo/contatti',
    '/chi-siamo/condizioni-di-vendita',

    '/arredi',
    '/arredi/lampadari',
    '/arredi/quadri',
    '/arredi/soprammobili',

    '/edilizia',
    '/edilizia/antimuffa',
    '/edilizia/demolizioni',
    '/edilizia/impermeabilizzazioni',
    '/edilizia/indoratura',
    '/edilizia/intonaci',
    '/edilizia/massetti',
    '/edilizia/opere-murarie',
    '/edilizia/pavimenti',
    '/edilizia/piastrelle',
    '/edilizia/piscine',
    '/edilizia/pitturazioni',
    '/edilizia/pulizia-finale',
    '/edilizia/sanitari',
    '/edilizia/smaltimento-calcinacci',
    '/edilizia/solarium',
    '/edilizia/tetti',
    '/edilizia/tinteggiatura',
    '/edilizia/tracce',
    '/edilizia/tramezzature',

    '/elettricita',
    '/elettricita/domotica',
    '/elettricita/elettrodomestici',
    '/elettricita/illuminazione',
    '/elettricita/impianti-elettrici',
    '/elettricita/pannelli-solari',
    '/elettricita/videosorveglianza',

    '/legno',
    '/legno/cucine',
    '/legno/infissi-in-legno',
    '/legno/mobili-in-massello',
    '/legno/mobili-tamburati',
    '/legno/parquet',
    '/legno/porte-interne',
    '/legno/porte-scrigno',
    '/legno/rivestimento-compensato',

    '/metallurgia',
    '/metallurgia/armadi-blindati',
    '/metallurgia/balconi',
    '/metallurgia/cancelli',
    '/metallurgia/casseforti',
    '/metallurgia/grate',
    '/metallurgia/grondaie',
    '/metallurgia/porte-antincendio',
    '/metallurgia/porte-blindate-legno',
    '/metallurgia/porte-blindate-alluminio',
    '/metallurgia/porte-blindate-pvc',
    '/metallurgia/porte-corazzate',
    '/metallurgia/ringhiere',
    '/metallurgia/saracinesche-manuali',
    '/metallurgia/saracinesche-motorizzate',
    '/metallurgia/scale',
    '/metallurgia/scale-a-chiocciola',
    '/metallurgia/scale-antincendio',
    '/metallurgia/scale-a-rampe',
    '/metallurgia/strutture',
    '/metallurgia/tetti-coibentati',

    '/serramenti',
    '/serramenti/infissi-in-alluminio-taglio-termico',
    '/serramenti/infissi-in-alluminio-freddo',
    '/serramenti/avvolgibili-motorizzati',
    '/serramenti/box-doccia',
    '/serramenti/monoblocchi',
    '/serramenti/cassonetti-in-pvc',
    '/serramenti/infissi-in-pvc',
    '/serramenti/infissi-in-legno-alluminio',
    '/serramenti/lucernai',
    '/serramenti/persiane-in-alluminio',
    '/serramenti/persiane-in-pvc',
    '/serramenti/pergole-bioclimatiche',
    '/serramenti/tapparelle-in-alluminio',
    '/serramenti/tapparelle-in-pvc',
    '/serramenti/tapparelle-motorizzazione',
    '/serramenti/veneziane',
    '/serramenti/verande',
    '/serramenti/verande-in-alluminio',
    '/serramenti/verande-in-pvc',
    '/serramenti/vetrate-panoramiche',
    '/serramenti/vetrine',
    '/serramenti/zanzariere',

    '/servizi',
    '/servizi/contratti-di-pulizia',
    '/servizi/manutenzione',
    '/servizi/montaggio',
    '/servizi/riparazioni',

    '/termodinamica',
    '/termodinamica/allacci',
    '/termodinamica/caldaie',
    '/termodinamica/climatizzazione',
    '/termodinamica/impianti-idraulici',
    '/termodinamica/irrigazione',
    '/termodinamica/isolamenti-acustici',
    '/termodinamica/isolamenti-termici',
    '/termodinamica/pompe-di-calore',

    '/tessuti',
    '/tessuti/divani',
    '/tessuti/tendaggi',
  ]

  return staticRoutes.map(route => ({
    url: `${BASE}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '/' ? 'weekly' : 'monthly',
    priority: route === '/' ? 1 : route.split('/').length === 2 ? 0.8 : 0.6,
  }))
}
